name: indexer-update-from-file

on:
  workflow_dispatch:

jobs:
  update-indexer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: heyitsmemark/update-azure-search-indexer@1.0.0
        with:
          azureSearchInstance: plop
          azureSearchAdminKey: ${{ secrets.AZURE_SEARCH_ADMIN_KEY }}
          indexerName: indexer-plop
          indexerDefinitionFile: ./test-definitions/indexer.json